### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ZoomRmc** [a8m/pb#17]
At the moment pbr compiles and kind of works, but produces new line on each update.

Looks like this:

```
3053 / 305308 [>-------------------------------------------------] 1.00 % 25171907.72/s 0s
6106 / 305308 [>-------------------------------------------------] 2.00 % 20251468.45/s 0s
9159 / 305308 [=>------------------------------------------------] 3.00 % 18664107.20/s 0s
...
```
Windows support would be much appreciated.

**Comment by Geemili** [comment]
I think I found out what the issue is.

When I capture the output in a file and the call `cat file_name_here.txt`, the progress bars show up fine. That means that the `\r` is being inserted correctly, so I dug into the source code.

It turns out that the line is being wrapped onto the next line. When I change `w as usize` on line 273 of `pb.rs` to `w as usize - 1` the output looks fine.

I would make a pull request, but if there is a less hacky way to fix this, I want to try that first.
